name: Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    uses: clouddrove/github-shared-workflows/.github/workflows/tag-release.yml@feat/tag-release
    with:
      target_branch: master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
